export const topics = [
  "Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "Computer Science",
  "Literature",
  "History",
  "Philosophy",
  "Psychology",
  "Sociology",
  "Economics",
  "Business",
  "Art",
  "Music",
  "Film Studies",
  "Environmental Science",
  "Political Science",
  "Linguistics",
  "Anthropology",
  "Engineering",
  "Pre-Med",
];
